-- phpMyAdmin SQL Dump
-- version 4.0.4.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 02, 2015 at 07:56 PM
-- Server version: 5.5.32
-- PHP Version: 5.4.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `roboticsdatabase`
--
CREATE DATABASE IF NOT EXISTS `roboticsdatabase` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `roboticsdatabase`;

-- --------------------------------------------------------

--
-- Table structure for table `attendence_event`
--
-- Creation: Dec 01, 2015 at 08:37 PM
--

DROP TABLE IF EXISTS `attendence_event`;
CREATE TABLE IF NOT EXISTS `attendence_event` (
  `attend_id` int(15) NOT NULL AUTO_INCREMENT,
  `remarks` varchar(255) NOT NULL,
  `attend_time` time DEFAULT NULL,
  `leave_time` time DEFAULT NULL,
  PRIMARY KEY (`attend_id`),
  KEY `attend_id` (`attend_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `brac_dept`
--
-- Creation: Nov 06, 2015 at 12:41 PM
--

DROP TABLE IF EXISTS `brac_dept`;
CREATE TABLE IF NOT EXISTS `brac_dept` (
  `bdept_id` int(15) NOT NULL,
  `Depertment_name` varchar(255) NOT NULL,
  PRIMARY KEY (`bdept_id`),
  KEY `Depertment_name` (`Depertment_name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `event_table`
--
-- Creation: Dec 01, 2015 at 08:18 PM
--

DROP TABLE IF EXISTS `event_table`;
CREATE TABLE IF NOT EXISTS `event_table` (
  `event_id` int(15) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Event Id Autogenerated ',
  `event_name` varchar(255) NOT NULL COMMENT 'Name of the Event',
  `event_desc` varchar(255) NOT NULL COMMENT 'Description like host , Activity',
  `event_date` date NOT NULL,
  `start_time` time NOT NULL COMMENT 'start time of Event',
  `end_time` time NOT NULL COMMENT 'End Time on event',
  `place` varchar(255) NOT NULL COMMENT 'Location of the Event',
  `Amount_pay` int(15) NOT NULL COMMENT 'Amount to Pay ',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`event_id`),
  KEY `event_id` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `post_descriptin`
--
-- Creation: Nov 06, 2015 at 12:41 PM
--

DROP TABLE IF EXISTS `post_descriptin`;
CREATE TABLE IF NOT EXISTS `post_descriptin` (
  `Post_id` int(15) NOT NULL,
  `Post_name` varchar(255) NOT NULL,
  `holder_name` varchar(255) NOT NULL,
  PRIMARY KEY (`Post_id`),
  KEY `Post_name` (`Post_name`),
  KEY `Post_name_2` (`Post_name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `project description`
--
-- Creation: Nov 06, 2015 at 12:41 PM
--

DROP TABLE IF EXISTS `project description`;
CREATE TABLE IF NOT EXISTS `project description` (
  `proj_id` int(15) NOT NULL AUTO_INCREMENT,
  `P_Name` varchar(255) NOT NULL,
  `Proj_desc` varchar(255) NOT NULL,
  `Proj_Destination` varchar(255) NOT NULL,
  `Current_status` tinyint(1) NOT NULL,
  `timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`proj_id`),
  UNIQUE KEY `P_Name` (`P_Name`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2015105 ;

-- --------------------------------------------------------

--
-- Table structure for table `robu_dept`
--
-- Creation: Nov 06, 2015 at 12:41 PM
--

DROP TABLE IF EXISTS `robu_dept`;
CREATE TABLE IF NOT EXISTS `robu_dept` (
  `rdept_id` int(15) NOT NULL,
  `rdept_name` varchar(255) NOT NULL,
  PRIMARY KEY (`rdept_id`),
  KEY `rdept_id` (`rdept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `std_attend_event`
--
-- Creation: Dec 01, 2015 at 08:29 PM
--

DROP TABLE IF EXISTS `std_attend_event`;
CREATE TABLE IF NOT EXISTS `std_attend_event` (
  `list_id` int(15) NOT NULL AUTO_INCREMENT,
  `std_id` int(15) NOT NULL,
  `event_id` int(15) NOT NULL,
  `attend_id` int(15) NOT NULL,
  PRIMARY KEY (`list_id`),
  KEY `std_id` (`std_id`,`event_id`,`attend_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- RELATIONS FOR TABLE `std_attend_event`:
--   `attend_id`
--       `attendence_event` -> `attend_id`
--   `event_id`
--       `event_table` -> `event_id`
--   `std_id`
--       `student_info` -> `std_id`
--

-- --------------------------------------------------------

--
-- Table structure for table `std_hold_clubdept`
--
-- Creation: Dec 02, 2015 at 04:04 PM
--

DROP TABLE IF EXISTS `std_hold_clubdept`;
CREATE TABLE IF NOT EXISTS `std_hold_clubdept` (
  `std_hold_clubdept` int(15) NOT NULL AUTO_INCREMENT,
  `rdept_id` int(15) NOT NULL,
  `std_id` int(15) NOT NULL,
  `post_id` int(15) NOT NULL,
  PRIMARY KEY (`std_hold_clubdept`),
  KEY `rdept_id` (`rdept_id`,`std_id`),
  KEY `std_id` (`std_id`),
  KEY `post_id` (`post_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- RELATIONS FOR TABLE `std_hold_clubdept`:
--   `post_id`
--       `post_descriptin` -> `Post_id`
--   `rdept_id`
--       `robu_dept` -> `rdept_id`
--   `std_id`
--       `student_info` -> `std_id`
--

-- --------------------------------------------------------

--
-- Table structure for table `std_hold_unidept`
--
-- Creation: Dec 02, 2015 at 04:03 PM
--

DROP TABLE IF EXISTS `std_hold_unidept`;
CREATE TABLE IF NOT EXISTS `std_hold_unidept` (
  `std_hold_unidept` int(15) NOT NULL AUTO_INCREMENT,
  `std_id` int(15) NOT NULL,
  `bdept_id` int(15) NOT NULL,
  PRIMARY KEY (`std_hold_unidept`),
  KEY `std_id` (`std_id`,`bdept_id`),
  KEY `bdept_id` (`bdept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- RELATIONS FOR TABLE `std_hold_unidept`:
--   `bdept_id`
--       `brac_dept` -> `bdept_id`
--   `std_id`
--       `student_info` -> `std_id`
--

-- --------------------------------------------------------

--
-- Table structure for table `student_info`
--
-- Creation: Nov 06, 2015 at 12:41 PM
--

DROP TABLE IF EXISTS `student_info`;
CREATE TABLE IF NOT EXISTS `student_info` (
  `std_id` int(15) NOT NULL COMMENT 'STUDENT ID OF BRAC UNIVERSITY',
  `Name` varchar(255) NOT NULL,
  `Skill` varchar(255) NOT NULL,
  `Interest` varchar(255) NOT NULL,
  `phone` int(11) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`std_id`),
  UNIQUE KEY `std_id` (`std_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `user`
--
-- Creation: Nov 06, 2015 at 12:41 PM
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` int(15) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `user_lvl` int(2) NOT NULL DEFAULT '1',
  `std_id` int(15) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `email` (`email`),
  KEY `std_id` (`std_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6 ;

--
-- RELATIONS FOR TABLE `user`:
--   `std_id`
--       `student_info` -> `std_id`
--

-- --------------------------------------------------------

--
-- Table structure for table `workson`
--
-- Creation: Dec 01, 2015 at 07:09 PM
--

DROP TABLE IF EXISTS `workson`;
CREATE TABLE IF NOT EXISTS `workson` (
  `WorksId` int(15) NOT NULL,
  `proj_id` int(15) NOT NULL,
  `std_id` int(15) NOT NULL,
  PRIMARY KEY (`WorksId`),
  KEY `proj_id` (`proj_id`),
  KEY `std_id` (`std_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Student WorksOn Project ';

--
-- RELATIONS FOR TABLE `workson`:
--   `proj_id`
--       `project description` -> `proj_id`
--   `std_id`
--       `student_info` -> `std_id`
--

--
-- Constraints for dumped tables
--

--
-- Constraints for table `std_hold_clubdept`
--
ALTER TABLE `std_hold_clubdept`
  ADD CONSTRAINT `std_hold_clubdept_ibfk_3` FOREIGN KEY (`post_id`) REFERENCES `post_descriptin` (`Post_id`),
  ADD CONSTRAINT `std_hold_clubdept_ibfk_1` FOREIGN KEY (`rdept_id`) REFERENCES `robu_dept` (`rdept_id`),
  ADD CONSTRAINT `std_hold_clubdept_ibfk_2` FOREIGN KEY (`std_id`) REFERENCES `student_info` (`std_id`);

--
-- Constraints for table `std_hold_unidept`
--
ALTER TABLE `std_hold_unidept`
  ADD CONSTRAINT `std_hold_unidept_ibfk_2` FOREIGN KEY (`bdept_id`) REFERENCES `brac_dept` (`bdept_id`),
  ADD CONSTRAINT `std_hold_unidept_ibfk_1` FOREIGN KEY (`std_id`) REFERENCES `student_info` (`std_id`);

--
-- Constraints for table `user`
--
ALTER TABLE `user`
  ADD CONSTRAINT `user_ibfk_1` FOREIGN KEY (`std_id`) REFERENCES `student_info` (`std_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
